### ISSUE TITLE
Hello author

### ISSUE THREAD

**Issue by joyivan** [trevorfiez/The-Metropolitan-Museum-of-Art-Image-Downloader#1]
I want download all images from Met ,how to use your script to achieve the goal . thanks

**Comment by trevorfiez** [comment]
Are you sure you want to download every image? In practice when I downloaded images it took about 15 seconds per image including getting the download address.  If this is representative of how long it takes on your computer, it would take around 3 months to download and require over 2 terabytes of data.

**Comment by joyivan** [comment]
@trevorfiez I just want to try . after running your code, I have found a problem "met_csv = csv.reader(open(met_csv_file, 'rb'), delimiter=',')
IOError: [Errno 2] No such file or directory: ''
" 
it means that I coude type the csv file by type --csv option ?
but I don't have the file   and  I am a chinese and my english is not skilled   :)

**Comment by trevorfiez** [comment]
I provided an example in the readme with better instructions on how to run it. You do have to provide the csv file by doing either --csv=csv_file.csv or -i csv_file.csv.

**Comment by joyivan** [comment]
Thanks a lot
