### ISSUE TITLE
--type not working

### ISSUE THREAD

**Issue by robbiebarrat** [trevorfiez/The-Metropolitan-Museum-of-Art-Image-Downloader#2]
First off - I love your program - thanks for writing it!

Whenever I try to run

    python met_download.py --csv=MetObjects.csv --out=paintings --type "Oil paintings"

The only output I get is:

    []
    0

And sometimes there is an empty CSV file in the output directory... The script works with the --list argument (and it works very well), but not with --type. Help?

**Comment by trevorfiez** [comment]
Thanks!

The type you are using is not a type listed on the open access csv file. The type I think you are trying to use is "Oil on canvas". You can check the csv from the met for relevant types or check out their website, each piece has their type description. I also added support so you do not have to give an artist to query the csv file: 36e4b25fbf4c9d765a5192a8c769a0dd6260f929. So if you run:


`python met_download.py --csv=MetObjects.csv --out=paintings --type "Oil on canvas"`

It should work now

**Comment by robbiebarrat** [comment]
Thank you so much! It works great - I'm working on a generative art project right now, I'll credit you once I put it on my Github (could be a few weeks) for helping me get the data - how should I credit you?

**Comment by robbiebarrat** [comment]
Also - is there a list of the types of art hosted on MET somewhere? Just a list of the stuff I can pass as parameters through --type?
