### ISSUE TITLE
When running example script the return is -1 on console and no image

### ISSUE THREAD

**Issue by gbernal** [trevorfiez/The-Metropolitan-Museum-of-Art-Image-Downloader#3]
Hi,

@trevorfiez Thank you for sharing your code. I'm hopping to use it but when I run the script 
`python2 met_download.py --csv=collection/MetObjects.csv --out=some_dir  --artist="Claude Monet"
`

this is an excerpt from console output is 

Claude Monet Oil on canvas 438006
Claude Monet Oil on canvas 438007
Claude Monet Oil on canvas 438008
Claude Monet Oil on canvas 438435
Claude Monet Oil on canvas 438823
Claude Monet Oil on canvas 459107
Claude Monet Oil on canvas 680098
42
-1
-1
-1
-1
-1
-1
-1
-1
and in the output directory `some_dir` I only get an empyt csv file.

**Comment by gbernal** [comment]
I think I have figured out why, in the example provided `-artist="Claude Monet"` I don't think there are any images open source from this artist, same happens with the paintings.txt. I believe The MET has changed the images that are part of the public catalog. My issue now is that the images downloaded are corrupted or something like because I can't open them

**Comment by trudvangarer** [comment]
> I think I have figured out why, in the example provided `-artist="Claude Monet"` I don't think there are any images open source from this artist, same happens with the paintings.txt. I believe The MET has changed the images that are part of the public catalog. My issue now is that the images downloaded are corrupted or something like because I can't open them

Did you manage the issue in the end? I am stuck at the -1 error. Help will be really appreciated, I direly need many images from metmuseum for the studying. Thanks

**Comment by ohjay** [comment]
The Met has updated the HTML structure on its website. As of today, [this change](https://github.com/trevorfiez/The-Metropolitan-Museum-of-Art-Image-Downloader/pull/5/files) should fix things.

**Comment by wienerherz** [comment]
I am having the same issue with the fix :/
